import type { Provider } from '@/lib/supabase'

// ─── Demo providers ───────────────────────────────────────────────────────────
// Illustrative sample providers shown on /admin/providers when there's no live
// data yet, so the management view demos well. Mirrors the SQL seed. NOT real.
export const DEMO_PROVIDERS: Provider[] = [
  {
    id: 'demo-p1',
    name: 'Ravi Kumar',
    phone: '+91 98100 45612',
    profession: 'Senior Electrician',
    services: ['electrician', 'plumber'],
    areas: ['Delhi', 'Gurugram'],
    working_days: [1, 2, 3, 4, 5, 6],
    start_time: '08:00',
    end_time: '20:00',
    rating: 4.9,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-p2',
    name: 'Meena Iyer',
    phone: '+91 99710 33845',
    profession: 'Home Chef',
    services: ['home_chef'],
    areas: ['Bangalore', 'Mumbai'],
    working_days: [0, 1, 2, 3, 4, 5, 6],
    start_time: '10:00',
    end_time: '22:00',
    rating: 4.8,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-p3',
    name: 'Sunita Devi',
    phone: '+91 90045 11203',
    profession: 'House Help Lead',
    services: ['house_help'],
    areas: ['Gurugram', 'Noida', 'Delhi'],
    working_days: [1, 2, 3, 4, 5, 6],
    start_time: '07:00',
    end_time: '17:00',
    rating: 4.7,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-p4',
    name: 'Arjun Pillai',
    phone: '+91 98911 77520',
    profession: 'Plumbing Specialist',
    services: ['plumber', 'electrician'],
    areas: ['Mumbai'],
    working_days: [1, 2, 3, 4, 5],
    start_time: '09:00',
    end_time: '19:00',
    rating: 4.6,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-p5',
    name: 'Fatima Sheikh',
    phone: '+91 99580 66471',
    profession: 'Childcare Pro',
    services: ['babysitter'],
    areas: ['Bangalore', 'Mumbai', 'Noida'],
    working_days: [4, 5, 6, 0],
    start_time: '16:00',
    end_time: '23:00',
    rating: 5.0,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-p6',
    name: 'Deepak Verma',
    phone: '+91 90192 88134',
    profession: 'Dog Walker',
    services: ['dog_walker'],
    areas: ['Bangalore', 'Delhi'],
    working_days: [0, 1, 2, 3, 4, 5, 6],
    start_time: '06:00',
    end_time: '10:00',
    rating: 4.9,
    active: true,
    created_at: new Date().toISOString(),
  },
]
