import type { Booking } from '@/lib/supabase'

// ─── Demo bookings ────────────────────────────────────────────────────────────
// Illustrative sample orders shown on /admin when there is no live data yet,
// so the dashboard demos well during the prototype phase. NOT real customers.
// `created_at` is computed relative to now so the list always looks fresh.
const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString()

export const DEMO_BOOKINGS: Booking[] = [
  {
    id: 'demo-1',
    booking_display_id: 'DDD-20260531-ABCD',
    user_phone: '+91 98100 12345',
    user_name: 'Aarav Sharma',
    service_type: 'home_chef',
    area: 'Indiranagar, Bangalore',
    slot_date: 'today',
    slot_time: '7:00 PM – 9:00 PM',
    address: '402, Brigade Towers, 12th Main',
    landmark: 'Opp. Indiranagar Metro',
    notes: 'North Indian dinner for 4. No onion/garlic.',
    provider_id: 'demo-p2',
    provider_name: 'Meena Iyer',
    payment_status: 'success',
    payment_link: null,
    amount_paid: 499,
    payment_method: 'UPI',
    razorpay_payment_id: 'pay_demo_1',
    transaction_timestamp: minsAgo(7),
    status: 'provider_confirmed',
    created_at: minsAgo(8),
  },
  {
    id: 'demo-2',
    booking_display_id: 'DDD-20260531-EFGH',
    user_phone: '+91 99710 88221',
    user_name: 'Priya Nair',
    service_type: 'house_help',
    area: 'DLF Phase 3, Gurugram',
    slot_date: 'tomorrow',
    slot_time: '9:00 AM – 11:00 AM',
    address: 'Villa 27, Westend Heights',
    landmark: 'Near Cyber Hub',
    notes: 'Deep cleaning + dishes.',
    provider_id: 'demo-p3',
    provider_name: 'Sunita Devi',
    payment_status: 'pending',
    payment_link: 'https://rzp.io/i/demo27',
    amount_paid: null,
    payment_method: null,
    razorpay_payment_id: null,
    transaction_timestamp: null,
    status: 'confirmed',
    created_at: minsAgo(23),
  },
  {
    id: 'demo-3',
    booking_display_id: 'DDD-20260531-IJKL',
    user_phone: '+91 90045 56789',
    user_name: 'Rohan Mehta',
    service_type: 'electrician',
    area: 'Powai, Mumbai',
    slot_date: 'today',
    slot_time: 'ASAP',
    address: 'B-1104, Lake Homes',
    landmark: 'Behind Hiranandani',
    notes: 'Geyser not heating + 2 fan regulators.',
    provider_id: 'demo-p4',
    provider_name: 'Arjun Pillai',
    payment_status: 'success',
    payment_link: null,
    amount_paid: 499,
    payment_method: 'Card',
    razorpay_payment_id: 'pay_demo_3',
    transaction_timestamp: minsAgo(39),
    status: 'completed',
    created_at: minsAgo(41),
  },
  {
    id: 'demo-4',
    booking_display_id: 'DDD-20260531-MNOP',
    user_phone: '+91 98911 33042',
    user_name: 'Ananya Gupta',
    service_type: 'babysitter',
    area: 'Sector 50, Noida',
    slot_date: 'weekend',
    slot_time: '6:00 PM – 11:00 PM',
    address: 'A-302, Mahagun Moderne',
    landmark: 'Near Logix City Centre',
    notes: 'Two kids (4 & 7). Date night.',
    provider_id: 'demo-p5',
    provider_name: 'Fatima Sheikh',
    payment_status: 'pending',
    payment_link: 'https://rzp.io/i/demo50',
    amount_paid: null,
    payment_method: null,
    razorpay_payment_id: null,
    transaction_timestamp: null,
    status: 'needs_manual_assignment',
    created_at: minsAgo(72),
  },
  {
    id: 'demo-5',
    booking_display_id: 'DDD-20260531-QRST',
    user_phone: '+91 99580 21176',
    user_name: 'Vikram Singh',
    service_type: 'plumber',
    area: 'Hauz Khas, Delhi',
    slot_date: 'tomorrow',
    slot_time: '11:00 AM – 1:00 PM',
    address: 'C-14, SDA Market Road',
    landmark: 'Above HDFC Bank',
    notes: 'Kitchen sink leak under cabinet.',
    provider_id: 'demo-p1',
    provider_name: 'Ravi Kumar',
    payment_status: 'success',
    payment_link: null,
    amount_paid: 499,
    payment_method: 'WhatsApp Pay',
    razorpay_payment_id: 'pay_demo_5',
    transaction_timestamp: minsAgo(116),
    status: 'confirmed',
    created_at: minsAgo(118),
  },
  {
    id: 'demo-6',
    booking_display_id: 'DDD-20260531-UVWX',
    user_phone: '+91 90192 44530',
    user_name: 'Sneha Reddy',
    service_type: 'dog_walker',
    area: 'Koramangala, Bangalore',
    slot_date: 'today',
    slot_time: '6:30 AM – 7:00 AM',
    address: '5th Block, 80 Feet Road',
    landmark: 'Near Forum Mall',
    notes: 'Golden Retriever, morning walk.',
    provider_id: 'demo-p6',
    provider_name: 'Deepak Verma',
    payment_status: 'success',
    payment_link: null,
    amount_paid: 499,
    payment_method: 'UPI',
    razorpay_payment_id: 'pay_demo_6',
    transaction_timestamp: minsAgo(163),
    status: 'provider_confirmed',
    created_at: minsAgo(165),
  },
  {
    id: 'demo-7',
    booking_display_id: 'DDD-20260531-YZAA',
    user_phone: '+91 98330 67219',
    user_name: 'Kabir Khanna',
    service_type: 'home_chef',
    area: 'Bandra West, Mumbai',
    slot_date: 'weekend',
    slot_time: '12:00 PM – 3:00 PM',
    address: '7th Flr, Pali Hill Residency',
    landmark: 'Off Carter Road',
    notes: 'House party, 10 guests. Continental.',
    provider_id: null,
    provider_name: null,
    payment_status: 'pending',
    payment_link: 'https://rzp.io/i/demoPH',
    amount_paid: null,
    payment_method: null,
    razorpay_payment_id: null,
    transaction_timestamp: null,
    status: 'cancelled',
    created_at: minsAgo(240),
  },
]
